
package com.mycompany.modeloia;
import com.mycompany.modeloia.CoCeTree;
import com.mycompany.modeloia.BarraAccesoRapido;
import com.mycompany.modeloia.InventarioPrincipalGUI;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;


public class SWLMmain extends javax.swing.JFrame {
    private JPanel mainPanel;
    private InventarioPrincipalGUI inventario;
    private BarraAccesoRapido barraAcceso;

    public SWLMmain() {

        setTitle("SWLM Main");
        setSize(1000, 800);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        
        
        barraAcceso = new BarraAccesoRapido();
        
       
        JPanel topPanel = new JPanel();
        topPanel.setBackground(new Color(10, 50, 100));
        topPanel.setLayout(new FlowLayout(FlowLayout.LEFT));

        JButton btnTree = new JButton("Tree");
        JButton btnChestroom = new JButton("Chestroom");
        JButton btnSearch = new JButton("Search");

        topPanel.add(btnTree);
        topPanel.add(btnChestroom);
        topPanel.add(btnSearch);

        mainPanel = new JPanel();
        mainPanel.setBackground(Color.RED);
        mainPanel.setLayout(new BorderLayout());


        btnTree.addActionListener(e -> switchPanel(new JScrollPane(new CoCeTree())));
        btnChestroom.addActionListener(e -> switchPanel(createFullInventoryPanel()));
        btnSearch.addActionListener(e -> switchPanel(getIteamSearchContent()));


        setLayout(new BorderLayout());
        add(topPanel, BorderLayout.NORTH);
        add(mainPanel, BorderLayout.CENTER);
    

    }
    private InventarioPrincipalGUI inventarioInstance = null;
private JComponent getIteamSearchContent() {
    ItemSearch searchFrame = new ItemSearch(); // Asegúrate de que este constructor funcione
    JPanel contentPanel = searchFrame.getContentPanel(); // Método para obtener el contenido
    return contentPanel;
}
    
    private JScrollPane createFullInventoryPanel() {
       JPanel container = new JPanel();
    container.setLayout(new BoxLayout(container, BoxLayout.Y_AXIS));

   
    container.add(barraAcceso.getContentPane());

    JScrollPane scrollPane = new JScrollPane(container);
    scrollPane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
    scrollPane.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);

    return scrollPane;
    }
        private void switchPanel(JComponent newContent) {
        mainPanel.removeAll();
        mainPanel.add(newContent, BorderLayout.CENTER);
        mainPanel.revalidate();
        mainPanel.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SWLMmain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SWLMmain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SWLMmain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SWLMmain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

       SwingUtilities.invokeLater(() -> {
            SWLMmain frame = new SWLMmain();
            frame.setVisible(true);
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
